services:
  - type: web
    name: incentive-management-system
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: SKIP_INSTALL_DEPS
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html